services:
  - type: web
    name: inco-host
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
      
